server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /api/authservice
  config:
    import: optional:env/env.properties
jwt:
  key:
    secret: ${SECRET:#{null}}
    signature: BeqbvWM1mem/MP887bU919s3AAQmFl6cdanzq5h7LZof9Cz2XsQcAXGuqGziW6t0zAkoB6bevoj/JYN/4sIPjWKoibQr3YsigC4Fiip6CN0=

leagueapi:
  services:
    paths-without-authentication: /authentication/authenticate, /authentication/signup
