server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /api/authservice
  config:
    import: optional:env/env.properties
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/authservice
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  key:
    secret: ${SECRET:#{null}}
    signature: BeqbvWM1mem/MP887bU919s3AAQmFl6cdanzq5h7LZof9Cz2XsQcAXGuqGziW6t0zAkoB6bevoj/JYN/4sIPjWKoibQr3YsigC4Fiip6CN0=

leagueapi:
  services:
    paths-without-authentication: /authentication/authenticate, /authentication/signup

