server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /api/authservice
  config:
    import: optional:env/env.properties
jwt:
  key:
    secret: ${SECRET:#{null}}
    signature: nizUAflm9tROvVK9E7oAA2Xj7trLKS0SWWfJ3F5QHEd2YJTLCrDmlyLqH8X6RTHPze0KXD757BkqT2w9d2IdN8rm0SuTzZPTNX+u0gZR/IE=
